version: '3'
services:
    storage:
        image: redis
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        expose:
            - 6379

    app:
        build: ./
        volumes:
            - ./:/var/www/app
        links:
            - storage
        ports:
            - ${LISTEN_PORT}:${LISTEN_PORT}
        environment:
            - NODE_ENV=development
        command: yarn start
